[package]
name = "empede-tide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
askama = "0.12.0"
askama_tide = "0.15.0"
async-std = { version = "1.12.0", features = ["attributes"] }
mpdrs = "0.1.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_qs = "0.12.0"
tide = "0.16.0"
tide-tracing = "0.0.12"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
