name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest]
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Strip
      if: runner.os == 'Linux'
      run: strip target/release/empede
    - name: Move binary
      if: runner.os == 'Linux'
      run: |
        mkdir empede
        mv README.md empede/
        mv target/release/empede empede/
        mv static/ empede/
        tar czf empede.tar.gz empede/
    - name: Move binary
      if: runner.os == 'Windows'
      run: |
        mkdir empede
        mv README.md empede\
        mv target\release\empede.exe empede\
        mv static\ empede\
        Compress-Archive -Path empede -DestinationPath empede.zip
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: target
        path: empede.*
    - uses: ncipollo/release-action@v1
      with:
        artifacts: empede.*
